
# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
name = "José Silva"
location = "Porto, Portugal"
description = "Cloud Network Engineer. Automation Enthusiast. I design high-performance datacenter networks, integrate security, and streamline both deployments and ops with code."
profile_image = "/images/profile.jpg"
github = "https://github.com/SojeLavis"
github_username = "sojelavis"
linkedin = "https://www.linkedin.com/in/josesilv/"
linkedin_username = "josesilv"

[[params.experience]]
company = "Microsoft"
role = "Cloud Network Engineer II"
period = "Jan 2023 - Present"
description = "Focused on Azure Networking, IaaS, and network automation"

[[params.experience]]
company = "Microsoft"
role = "Azure Networking Support Engineer"
period = "Dec 2021 - Feb 2023"
description = "Provided support for Azure infrastructure and networking services"

[[params.experience]]
company = "Axians Portugal (Vodafone PT)"
role = "Senior Network Support Specialist"
period = "Jun 2020 - Jan 2022"
description = "Support to Field Service teams during implementations. Implemented and troubleshooted solutions and services."

[[params.experience]]
company = "Axians Portugal (Vodafone PT)"
role = "Network Support Specialist"
period = "Dec 2019 - Jun 2020"
description = "Assisted with network support and troubleshooting for client environments."

[[params.experience]]
company = "Axians Portugal (Vodafone PT)"
role = "Network Support Specialist (Intern)"
period = "Sep 2019 - Dec 2019"
description = "Contributed to network configuration and monitoring activities during internship."

[[params.certifications]]
title = "DevNet Class of 2020 – Cisco DevNet"
date = "Sep 2020 - Now"

[[params.certifications]]
title = "Cisco Certified DevNet Professional"
date = "Jun 2024 - Now"

[[params.certifications]]
title = "Cisco Certified DevNet Associate"
date = "Oct 2020 - Now"

[[params.certifications]]
title = "Cisco Certified Networking Professional – Enterprise"
date = "Jan 2021 - JNow"

[[params.certifications]]
title = "Cisco Certified Specialist – Enterprise Design"
date = "2024 - Now"

[[params.certifications]]
title = "Cisco Certified Specialist – Enterprise Advanced Infrastructure Implementation"
date = "2024 - Now"

[[params.certifications]]
title = "Cisco Certified Network Associate (CCNA R&S)"
date = "Jan 2020 - Now"

[[params.certifications]]
title = "Microsoft Certified: Azure Fundamentals"
date = "2023 - Now"

[[params.certifications]]
title = "Azure Network Engineer Associate"
date = "Apr 2022 - Apr 2023"

[[params.certifications]]
title = "IT Service Management – AXELOS Global Best Practice"
date = "Jun 2020"

[[params.projects]]
title = "TBD"
description = "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae."
tech = "TypeScript, React, GraphQL, Docker"
image = "/images/projects/django.png"
link = "https://github.com/sojelavis"


[menu]
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 1
  [[menu.main]]
    name = "Certifications"
    url = "#certifications"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 3